### PR TITLE
Add new mod: Ixrec.ArchipelagoRandomizer

### LINKED ISSUE #802: Archipelago Randomizer
### Your Discord Name

ixrec

### Mod uniqueName

Ixrec.ArchipelagoRandomizer

### Mod name

Archipelago Randomizer

### GitHub repository URL

https://github.com/Ixrec/OuterWildsArchipelagoRandomizer

### Tags

gameplay, integration

### Author display name

Ixrec

### Parent uniqueName

_No response_

### DLC Required

None

### Alpha Mod

None

### PR DESCRIPTION
**Pull request by Raicuparta**
Closes #802
https://github.com/Ixrec/OuterWildsArchipelagoRandomizer

### CODE REVIEW

**Comment by Bwc9876** [comment]
It looks like the version in your manifest file is `0.1.0` but the tag of your release is `0.1.1`. This can make it so the mod manager will always see your mod as out-of-date

**Comment by Bwc9876** [comment]
It looks like the version in your manifest file is `0.1.0` but the tag of your release is `0.1.1`. This can make it so the mod manager will always see your mod as out-of-date

**Comment by MegaPiggy** [comment]
It looks like the version in your manifest file is `0.1.0` but the tag of your release is `0.1.1`. This can make it so the mod manager will always see your mod as out-of-date

**Comment by Ixrec** [comment]
Yes, I did make that mistake. Whenever I get back to developing this I'll be making a 0.1.2 release anyway, and I'll make sure to update the manifest this time.

**Review by xen-42 — CHANGES_REQUESTED** [review]
Blocking the pr until the changes idiot requested are implemented (fix manifest version number)

**Comment by Ixrec** [comment]
Sorry for the hiatus. Version 0.1.2 was just released, and this time I did update the manifest.json to say `"version": "0.1.2",` so this should be unblocked now.

**Review by xen-42 — APPROVED** [review]

**Pull request merged**
