### PR TITLE
Add new mod: MegaPiggy.CinematicUnityExplorer

### LINKED ISSUE #903: Cinematic Unity Explorer
### Your Discord Name

megapiggy

### Mod uniqueName

MegaPiggy.CinematicUnityExplorer

### Mod name

Cinematic Unity Explorer

### GitHub repository URL

https://github.com/MegaPiggy/Cinematic-Unity-Explorer-For-Outer-Wilds

### Tags

tool

### Author display name

MegaPiggy

### Parent uniqueName

_No response_

### DLC Required

None

### Alpha Mod

None

### PR DESCRIPTION
**Pull request by Raicuparta**
Closes #903 
https://github.com/MegaPiggy/Cinematic-Unity-Explorer-For-Outer-Wilds

### CODE REVIEW

**Comment by MegaPiggy** [comment]
oops

**Review by MegaPiggy — APPROVED** [review]

**Comment by Bwc9876** [comment]
checker, retry

**Comment by Bwc9876** [comment]
checker, retry

**Comment by Bwc9876** [comment]
checker, retry last time hopefully

**Pull request merged**
