### PR TITLE
Add new mod: TheLoreExplorer.GreenJetpack

### LINKED ISSUE #416: Green Jetpack
### Your Discord Name

loreexplorer#8072

### Mod uniqueName

Jetpack.ModTemplate

### Mod name

Green Jetpack

### GitHub repository URL

https://github.com/TheLoreExplorer/Jetpack.ModTemplate

### Author display name

The Lore Explorer

### Parent uniqueName

_No response_

### Utility mod

_No response_

### Alpha Mod

_No response_

### PR DESCRIPTION
**Pull request by Raicuparta**
Closes #416
https://github.com/TheLoreExplorer/Jetpack.ModTemplate

### CODE REVIEW

**Review by Bwc9876 — DISMISSED** [review]
lgtm

**Review by TerrificTrifid — APPROVED** [review]
lgtm

**Review by Nageld — DISMISSED** [review]
lgtm

**Review by ShoosGun — APPROVED** [review]
lgtm

**Review by xen-42 — CHANGES_REQUESTED** [review]
The unique name should be changed to fit the standard (i.e., TheLoreExplorer.GreenJetpack). Also, consider adding an image to your readme showing the mod in action (will be displayed on the website, the resolution has to be 3:1 width to height).

**Review by MegaPiggy — APPROVED** [review]
lgtm

**Pull request merged**
