### PR TITLE
Add new mod: Steini.IcelandicTranslation

### LINKED ISSUE #723: Icelandic Localization
### Your Discord Name

.saevar

### Mod uniqueName

Steini.IcelandicTranslation

### Mod name

Icelandic Localization

### GitHub repository URL

https://github.com/kksteini/OuterWildsIcelandic

### Tags

localization

### Author display name

Steini

### Parent uniqueName

_No response_

### Alpha Mod

None

### PR DESCRIPTION
**Pull request by Raicuparta**
Closes #723
https://github.com/kksteini/OuterWildsIcelandic

### CODE REVIEW

**Review by xen-42 — CHANGES_REQUESTED** [review]
You uploaded the zip in the description of your release but it should be attached as an asset instead else the mod manager wont be able to download it

**Comment by MegaPiggy** [comment]
@kksteini

**Comment by kksteini** [comment]
LMAO, what must've happened is that I dragged it into the description field instead of the binary attachment fields just below.
Thanks, fixed :)

**Comment by Raicuparta** [comment]
@kksteini A few more things:
The manifest.json file inside your zip has the version `0.1.0`, while your release tag is `0.4`. These two must always match, because the mod manager compares them to check if a mod needs to be updated. You can just delete and reupload the zip with the correct manifest. As it is now, the manager will always mark the mod as being outdated, so we'll wait until you fix it.

The description field of your repository will be used as the mod description on the mods website and on the manager. Just giving you a heads up, but you can keep the current description if you want.

If you have a README.md file in your repo, it will be used to generate the mod page on the mods website. Having some text there can make it easier for the mod to be found via google etc. Also not mandatory, just letting you know.

**Comment by kksteini** [comment]
Thank you kindly for taking the time.
I've fixed these and added a rudimentary Readme to the project.

Appreciate it :D

**Pull request merged**
