### PR TITLE
rename "Quality of Life Changes" to "QOL Features"

### PR DESCRIPTION
**Pull request by Owen013**
i promise this is the last rename

probably

### CODE REVIEW

**Comment by MegaPiggy** [comment]
King of renaming your mods

**Comment by MegaPiggy** [comment]
Personally I think it would be better to name it "Quality of Life Features"

**Comment by Owen013** [comment]
yeah you right

**Comment by xen-42** [comment]
The name doesnt match the manifest tho bc here its "Quality of Life" but in the manifest its "QOL"

**Comment by Owen013** [comment]
Does that mess with the database or something? I was just gonna change the manifest name in the next update. I thought that "name" just changed the display name of the mod in the manager. I haven't changed the uniqueName or anything like that.

**Comment by xen-42** [comment]
no, just the name will change when u download it and thats weird! but ok

**Review by xen-42 — APPROVED** [review]

**Comment by Owen013** [comment]
don't worry i fix it, thanks

**Pull request merged**
