### PR TITLE
Add new mod: FunkyShoeMan.ErnestoTakeover

### LINKED ISSUE #490: Did wrong, Please delete
### Your Discord Name

FunkyShoeMan#0001

### Mod uniqueName

FunkyShoeMan.ErnestoTakeover

### Mod name

Ernesto Takeover

### GitHub repository URL

https://github.com/FunkyShoeMan/Ernesto-Takeover

### Tags

content

### Author display name

FunkyShoeMan

### Parent uniqueName

xen.NewHorizons

### Utility mod

_No response_

### Alpha Mod

_No response_

### PR DESCRIPTION
**Pull request by Raicuparta**
Closes #490
https://github.com/FunkyShoeMan/Ernesto-Takeover

### CODE REVIEW

**Comment by Bwc9876** [comment]
You have no releases on your repo, the manager won't be able to display the mod.

**Review by Bwc9876 — CHANGES_REQUESTED** [review]
No Releases >:(

**Comment by FunkyShoeMan** [comment]
close this please i messed it up

**Review by xen-42 — APPROVED** [review]
sure

**Pull request merged**
