### PR TITLE
Add new mod: nice2cu1.OuterWildFixFont

### LINKED ISSUE #662: OuterWildsFixFont
### Your Discord Name

_No response_

### Mod uniqueName

nice2cu1.OuterWildFixFont

### Mod name

Outer Wilds Chinese Fix

### GitHub repository URL

https://github.com/nice2cu1/OuterWildFixFont

### Tags

localization

### Author display name

_No response_

### Parent uniqueName

_No response_

### Utility mod

None

### Alpha Mod

None

### PR DESCRIPTION
**Pull request by Raicuparta**
Closes #662
https://github.com/nice2cu1/OuterWildFixFont

### CODE REVIEW

**Review by xen-42 — CHANGES_REQUESTED** [review]
What is this mod for?

**Comment by Raicuparta** [comment]
> What is this mod for?

Gotta ping the dude. @nice2cu1 please add some small description en English to the mod's reade, just so people know what this is about. You can leave the rest in Chinese if you want.

**Comment by xen-42** [comment]
Ah cool, I left an issue on the repo asking didn't realize you could just ping here

**Comment by nice2cu1** [comment]
> Ah cool, I left an issue on the repo asking didn't realize you could just ping here

I have used a translator to update the English description.

**Comment by xen-42** [comment]
Thank you!

**Review by xen-42 — APPROVED** [review]

**Pull request merged**
