### PR TITLE
Add new mod: atk.Hoarder

### LINKED ISSUE #924: Hoarder's Ship
### Your Discord Name

atk7639

### Mod uniqueName

atk.Hoarder

### Mod name

Hoarder's Ship

### GitHub repository URL

https://github.com/bruvin-sky/atk.Hoarder

### Tags

tweaks

### Author display name

_No response_

### Parent uniqueName

xen.NewHorizons

### DLC Required

None

### Alpha Mod

None

### PR DESCRIPTION
**Pull request by Raicuparta**
Closes #924
https://github.com/bruvin-sky/atk.Hoarder

### CODE REVIEW

**Comment by MegaPiggy** [comment]
checker, retry

**Comment by Bwc9876** [comment]
checker, retry

**Comment by Bwc9876** [comment]
checker, retry

**Comment by Bwc9876** [comment]
checker, retry

**Comment by Bwc9876** [comment]
checker, retry

**Comment by xen-42** [comment]
checker, retry

**Comment by xen-42** [comment]
checker, retry

**Review by xen-42 — APPROVED** [review]

**Pull request merged**
